#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 
# Starts Zookeeper for Hadoop HA
# 
# chkconfig: 2345 80 10
# description: Zookeeper for Hadoop HA

source /etc/profile.d/hadoop.sh
source /etc/profile.d/java.sh
source /etc/rc.d/init.d/functions
source ${HADOOP_HOME}/etc/hadoop/hadoop-env.sh
source /etc/profile.d/zookeeper.sh


RETVAL=0
PIDFILE="${HADOOP_PID_DIR}/hadoop-hdfs-datanode.pid"
desc="Zookeeper Quorum daemon"

start() {
  echo -n $"Starting $desc (hadoop-datanode): "
  if [ -n "$HADOOP_SECURE_DN_USER" ]; then
    daemon ${HADOOP_HOME}/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start datanode
  else
    daemon --user hdfs ${HADOOP_HOME}/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start datanode
  fi
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/hadoop-datanode
  return $RETVAL
}

stop() {
  echo -n $"Stopping $desc (hadoop-datanode): "
  if [ -n "$HADOOP_SECURE_DN_USER" ]; then
    daemon ${HADOOP_HOME}/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" stop datanode
  else
    daemon --user hdfs ${HADOOP_HOME}/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" stop datanode
  fi
  RETVAL=$?
  sleep 5
  echo
  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/hadoop-datanode $PIDFILE
}

restart() {
  stop
  start
}


case "$1" in
  start)
    $ZOOKEEPER_HOME/bin/zkServer.sh start
    ;;
  start-foreground)
    $ZOOKEEPER_HOME/bin/zkServer.sh start-foreground
    ;;
  stop)
    $ZOOKEEPER_HOME/bin/zkServer.sh stop
    ;;
  restart)
    $ZOOKEEPER_HOME/bin/zkServer.sh restart
    ;;
  status)
    $ZOOKEEPER_HOME/bin/zkServer.sh status
    ;;
  restart)
    $ZOOKEEPER_HOME/bin/zkServer.sh restart
    ;;
  upgrade)
    $ZOOKEEPER_HOME/bin/zkServer.sh upgrade
    ;;
  print-cmd)
    $ZOOKEEPER_HOME/bin/zkServer.sh print-cmd
    ;;
  *)
    echo $"Usage: $0 {start|start-foreground|stop|restart|status|upgrade|print-cmd}"
    exit 1
esac
