#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 
# Starts Zookeeper for Hadoop HA
# 
# chkconfig: 2345 80 10
# description: Zookeeper for Hadoop HA


source /etc/profile.d/java.sh
source /etc/profile.d/zookeeper.sh

RETVAL=0
desc="Zookeeper Quorum daemon"


case "$1" in
  start)
    $ZOOKEEPER_HOME/bin/zkServer.sh start
     RETVAL=$?
    ;;
  start-foreground)
    $ZOOKEEPER_HOME/bin/zkServer.sh start-foreground
     RETVAL=$?
    ;;
  stop)
    $ZOOKEEPER_HOME/bin/zkServer.sh stop
     RETVAL=$?
    ;;
  restart)
    $ZOOKEEPER_HOME/bin/zkServer.sh restart
     RETVAL=$?
    ;;
  status)
    $ZOOKEEPER_HOME/bin/zkServer.sh status
     RETVAL=$?
    ;;
  restart)
    $ZOOKEEPER_HOME/bin/zkServer.sh restart
     RETVAL=$?
    ;;
  upgrade)
    $ZOOKEEPER_HOME/bin/zkServer.sh upgrade
     RETVAL=$?
    ;;
  print-cmd)
    $ZOOKEEPER_HOME/bin/zkServer.sh print-cmd
     RETVAL=$?
    ;;
  *)
    echo $"Usage: $0 {start|start-foreground|stop|restart|status|upgrade|print-cmd}"
    exit 1
esac

exit $RETVAL